name: Test Work Flow

on:
  repository_dispatch:
    types:[test-event]
    
  workflow_dispatch:
    inputs:
        version:
          description: 'Version to deploy'
          required: true

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name:test step
        run: echo "Şu versiyon ${{inputs.version}}"
    
        
