name: Test Work Flow

on: 
  workflow_dispatch:
    inputs:
        version:
          description: 'Version to deploy'
          required: true
  repository_dispatch:
    types: [test-event]
          
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test-step: ${{steps.test-step.outputs}}
    steps:
      - name: test step
        id: test-step
        run: |
          echo "Deploying ${{ inputs.version }}"
